global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vitaly_ibragimov'
