version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ../src/ui
    image: ${USER_NAME}/ui:${UI_VER}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - back_net
      - front_net
  post:
    build: ../src/post-py
    image: ${USER_NAME}/post:${POST_VER}
    networks:
      - back_net
      - front_net
  comment:
    build: ../src/comment
    image: ${USER_NAME}/comment:${COMMENT_VER}
    networks:
      - back_net
      - front_net
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.4.0/24"
  front_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.3.0/24"
